const BASE_DIFFICULTY_MULTIPLIER = 10;

const POSTPONEMENT_MULTIPLIER = 2;

const FIRST_TIME_BONUS = 10;

const LEVEL_BREAKPOINTS = [
  0,
  75,
  150,
  250,
  375,
  525
]
export {
  BASE_DIFFICULTY_MULTIPLIER,
  POSTPONEMENT_MULTIPLIER,
  FIRST_TIME_BONUS,
  LEVEL_BREAKPOINTS
}